name: asre
version: '0.1.0'
config-version: 2

profile: asre

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

clean-targets:
  - target
  - dbt_packages
